# Generated by Django 5.2 on 2025-04-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cui_chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cuichat",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="cuimessage",
            options={"ordering": ["timestamp"]},
        ),
        migrations.AddField(
            model_name="cuichat",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="cuichat",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="cuimessage",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("assistant", "Assistant"),
                    ("system", "System"),
                ],
                max_length=20,
            ),
        ),
    ]
