# Generated by Django 5.2 on 2025-04-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cui_chat", "0002_alter_cuichat_options_alter_cuimessage_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CuiSystemPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("value", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
